# Generated by Django 3.1.2 on 2021-03-23 04:38

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCode',
            fields=[
                ('idciudad', models.AutoField(primary_key=True, serialize=False)),
                ('idregion', models.IntegerField(default=0)),
                ('idprovincia', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('citycode', models.CharField(blank=True, max_length=3, null=True)),
                ('idpais', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'ih_ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('idpais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('countrycode', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ih_pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombrepais', models.CharField(blank=True, max_length=30, null=True)),
                ('nombreciudad', models.CharField(blank=True, max_length=450, null=True)),
                ('venue', models.CharField(blank=True, max_length=600, null=True)),
                ('latitud', models.CharField(blank=True, max_length=60, null=True)),
                ('longitud', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'ih_venues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('pais', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado_del_evento', models.CharField(max_length=30, null=True)),
                ('tipo_del_evento', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField()),
                ('link_al_evento', models.CharField(max_length=255)),
                ('sitio_de_origen', models.CharField(max_length=40)),
                ('imagen', models.ImageField(max_length=2000, null=True, upload_to='media/photos_events')),
                ('imagen_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('imagen_mini', models.ImageField(max_length=2000, null=True, upload_to='media/photos_events')),
                ('imagen_mini_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_final', models.DateTimeField(blank=True, null=True)),
                ('sede', models.CharField(blank=True, max_length=500, null=True)),
                ('timing', models.CharField(blank=True, max_length=100, null=True)),
                ('visitantes', models.CharField(blank=True, max_length=100, null=True)),
                ('expositores', models.CharField(blank=True, max_length=100, null=True)),
                ('participantes', models.IntegerField(blank=True, null=True)),
                ('modificado', models.BooleanField(blank=True, default=False)),
                ('enviado', models.BooleanField(blank=True, default=False)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('sitio_web', models.CharField(blank=True, max_length=2000, null=True)),
                ('datos_requeridos_completos', models.BooleanField(default=True)),
                ('id_api', models.IntegerField(blank=True, null=True)),
                ('categorias', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('codigo_de_ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.citycode')),
                ('codigo_de_pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web.countrycode')),
            ],
        ),
    ]
