# Generated by Django 3.1.2 on 2021-04-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('scraped', models.BooleanField(blank=True, default=False)),
                ('link', models.URLField(blank=True, max_length=2000, null=True)),
                ('saved_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
